geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'


urlpatterns = [
    #path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    #path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    #path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),

    #path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),




    #path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),

    #path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    #path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),

    #path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    #path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),

    #path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),


    path('orders/read/<int:pk>', adminapp.orders_list, name='admin_orders'),

    path('orders/status/<pk>/', adminapp.order_status, name='order_status'),
    path('orders/recover/<pk>/', adminapp.order_recover, name='order_recover'),

]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'


urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    # path('products/', mainapp.products, name="products"),
    # path('product/', mainapp.product, name="product"),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace="admin")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name="index"),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'



urlpatterns = [
   path('', ordersapp.OrderList.as_view(), name='orders_list'),
   path('forming/complete/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
   path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
   path('read/<pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
   path('update/<pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
   path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
   path('add/form/<pk>/', ordersapp.order_ajax, name='order_add'),
   path('product/<pk>/price/', ordersapp.get_product_price),
   path('max/quantity/<pk>/', ordersapp.get_product_quantity)

]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class ProductCategory(models.Model):
    name = models.CharField(max_length=60, verbose_name="имя", unique=True)
    descriotion = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name="имя продукта")
    image = models.ImageField(upload_to="product_images", blank=True)
    short_desc = models.CharField(max_length=120, verbose_name="краткое описание продукта", blank=True)
    descriotion = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name="цена")
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True, db_index=True)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Gallery(models.Model):
    name_gallery = models.OneToOneField(Product, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    hot_image = models.ImageField(upload_to="hot_images", blank=True, default='hot_images/default.jpg')
    image_product = models.ImageField(upload_to="image_product", blank=True, default='image_product/default.jpg')

    @receiver(post_save, sender=Product)
    def create_gallery(sender, instance, created, **kwargs):
        if created:
            print('create')
            print(instance)

            Gallery.objects.create(name_gallery=instance)

    @receiver(post_save, sender=Product)
    def save_gallery(sender, instance, **kwargs):
        print(kwargs)

        print('save')
        instance.gallery.save()

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, ProductCategory, Gallery
from basketapp.models import Basket
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)

def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)

def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')

def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 2)[:2]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).filter(is_active=True).exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products

def hot_gallery(hot_game):
    hot_gallery = []
    for i in hot_game:
        print(i.name)
        image = Gallery.objects.filter(name_gallery=i.pk).select_related('name_gallery')
        print(hot_gallery.append(list(image)))
    return hot_gallery


def main(request):


    title = 'главная'
    list_game = get_products()[:4]
    content = {
        'games': list_game,
        "title": title,

    }
    return render(request, 'mainapp/index.html', content)

@cache_page(1)
def products(request, pk=None, page=1):
    count_product = 5

    title = 'галерея'
    list_categories = ProductCategory.objects.all()
    # hot_game = get_hot_product()
    # hot_image = hot_gallery(hot_game)
    #hot_image=[1,2]



    if pk is not None:
        if pk == 0:
            list_game = Product.objects.filter(is_active=True, category__is_active=True).order_by('price').select_related('category')
            category = {'name':'все', 'pk': 0}
        else:
            category = get_category(pk)
            print("+++")
            list_game = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(list_game, count_product)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
                'games': list_game,
                'categories': list_categories,
                "title": title,
                'pk_category': category,
                'products': products_paginator,

        }
        return render(request, 'mainapp/products_list.html', content)

    same_game = get_products()[1:4]

    content = {
        'games': same_game,
        'categories': list_categories,
        "title": title,
        #'hot_image': hot_image,

    }

    return render(request, 'mainapp/products.html', content)

@cache_page(1)
def product(request, pk):
    prod = get_product(pk)
    same_product = get_same_products(prod)
    print(same_product)
    title = 'продукты'
    img_gallery = Gallery.objects.filter(name_gallery=pk).select_related('name_gallery')
    # print(img_gallery[0].name_gallery, 'fdsfdsafa')
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'img_gallery': img_gallery,
        'same_product': same_product
    }
    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_header_list.html
{% load static %}
<div class="header-list">
    <a href="{% url 'main' %}"><div class="logo">
        <h2 class="logo-h2">Historical</h2>
        <p class="logo-p">GAMES</p>
    </div></a>
    <div class="telefon"> <img src="/static/img/telefon.png" alt="" class="logo-telefon">
        <p class="number">+123 456 7890</p>
    </div>
    <div class="email-list"> <img src="/static/img/email.png" alt="" class="logo-telefon">
        <p class="email">info@example.com</p>
    </div>
    <div class="find">
        <table>
            <tr>
                <td class="inputsab">
                    <input type="sabmit" value="Search" class="find-sabmit"> </td>
                <td class="search">
                    <a href="#"><img src="/static/img/find.png" alt=""></a>
                </td>
            </tr>
        </table>
    </div>
    <div class="list_log">
        {% if user.is_authenticated %}

            <li>
                <a href="{% url 'basket:view' %}" class="login_logout nickname">
                    {% if basket %}
                        {{ basket.0.total_cost|floatformat:0 }}$
                        {{ basket.0.total_quantity }}

                    {% endif %}

                </a>
            </li>
        {% endif%}
        <a href="{% url 'basket:view' %}" class="login_logout nickname">
            <img src="{% static 'img/shop.png' %}" alt="">
        </a>
        {% if user.is_authenticated %}
               {% if user.is_superuser %}
                <li>
                  <a href="{% url 'admin:users' %}" class="login_logout nickname">админка</a>
                </li>
               {% else %}
                     <li>
                   <div class="dropdown" style="margin-top: 0px;
    width: 100px;">
                       <a class="login_logout nickname" href="" data-toggle="dropdown">
                           {{ user.first_name|default:'Пользователь' }}
                           <span class="caret"></span>
                       </a>
                       <ul class="dropdown-menu">
                           <li>
                               <a href="{% url 'auth:edit' %}">
                                   профиль
                               </a>
                           </li>
                           <li>
                               <a href="{% url 'ordersapp:orders_list' %}">
                                   заказы
                               </a>
                           </li>
                       </ul>
                   </div>
               </li>

              {% endif %}

        {% endif%}

        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'auth:logout' %}" class="login_logout">Logout</a>
        {% else %}
          <a href="{% url 'auth:login' %}" class="login_logout">Login</a>
        {% endif %}
        </li>
    </div>



</div>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<ul class="menu-list">
    <li><a href="{% url 'main' %}" class="menu-link link-activ">Home</a></li>
    <li><a href="#" class="menu-link">About</a></li>
    <li><a href="#" class="menu-link">Services</a></li>
    <li><a href="{% url 'products:index' %}" class="menu-link">Gallery</a></li>
    <li><a href="#" class="menu-link">News</a></li>
    <li><a href="#" class="menu-link">Team</a></li>
    <li><a href="#" class="menu-link">Contact Us</a></li>
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu_catalogs.html
<ul class="menu-list">
    <li><a href="{% url 'main' %}" class="menu-link catalog-text ">Home</a></li>
    <li><a href="#" class="menu-link catalog-text">About</a></li>
    <li><a href="#" class="menu-link catalog-text">Services</a></li>
    <li><a href="{% url 'products:index' %}" class="menu-link catalog-text activ-catalog">Gallery</a></li>
    <li><a href="#" class="menu-link catalog-text">News</a></li>
    <li><a href="#" class="menu-link catalog-text">Team</a></li>
    <li><a href="#" class="menu-link catalog-text">Contact Us</a></li>
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu_gallery.html
<ul class="menu-list">

    <li class="menu-link catalog-text">
            <a href="{% url 'products:category' 0 %}"
       class=" menu-link catalog-text  {% if request.resolver_match.kwargs.pk == 0 %}
                active_category
              {% endif %}">
      все
    </a>

    </li>



    {% for category in categories %}
        <li><a href="{% url 'products:category' category.pk %}"class=" menu-link catalog-text  {% if request.resolver_match.kwargs.pk == category.pk %}
                active_category
              {% endif %}">{{ category.name}}</a></li>
    {% endfor %}

</ul>