geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'


urlpatterns = [
    #path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    #path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    #path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),

    #path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),




    #path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),

    #path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    #path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),

    #path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    #path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),

    #path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),


    path('orders/read/<int:pk>', adminapp.orders_list, name='admin_orders'),

    path('orders/status/<pk>/', adminapp.order_status, name='order_status'),
    path('orders/recover/<pk>/', adminapp.order_recover, name='order_recover'),

]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    # path('products/', mainapp.products, name="products"),
    # path('product/', mainapp.product, name="product"),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace="admin")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'



urlpatterns = [
   path('', ordersapp.OrderList.as_view(), name='orders_list'),
   path('forming/complete/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
   path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
   path('read/<pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
   path('update/<pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
   path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
   path('add/form/<pk>/', ordersapp.order_ajax, name='order_add'),
   path('product/<pk>/price/', ordersapp.get_product_price),
   path('max/quantity/<pk>/', ordersapp.get_product_quantity)

]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/ordersapp/models.py
from django.db import models

from django.db import models
from django.conf import settings
from mainapp.models import Product

# class OrderItemQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for object in self:
#             object.product.quantity += object.quantity
#             object.product.save()
#         super(OrderItemQuerySet, self).delete(*args, **kwargs)

class Order(models.Model):


    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES,  default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.orderitems.set = None

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)




    # cash
    def get_summary(self):
        items = self.orderitems.select_related()
        total_quantity = sum(list(map(lambda x: x.quantity, items)))
        total_cost = sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return {
            'total_cost': total_cost,
            'total_quantity': total_quantity,
        }

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    # objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product, Gallery


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        #fields = '__all__'
        exclude = ()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields.items())
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            #
            # if field_name == 'category':
            #     field.widget = forms.HiddenInput()

            # if field_name == 'category':
            #     self.fields['category'] = self.pk


class GalleryEditForm(forms.ModelForm):
    class Meta:
        model = Gallery
        #fields = '__all__'
        fields = ('hot_image', 'image_product')

    def __init__(self, *args, **kwargs):
        super(GalleryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>
    {% block title %}
    {% endblock %}

    {% block head %}
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_geek.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
      {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}

</head>

<body>
  <div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href="{% url 'admin:category_create' %}">
        новая категория
      </a>
    </button>
		
    {% for object in object_list %}
      <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href="{% url 'admin:products' object.pk %}">
              товары категории
            </a>
          </button>
          <button>
            <a href="{% url 'admin:category_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:category_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ category_to_delete.name }}
    ?
    <form action="{% url 'admin:category_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_title%}
<div class="h2 text-center head">
    Редактирование
</div>
{% endblock %}


{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}

   <table class="table orders_list" style="width: 1500px; margin-left: 200px;">
       <thead>
         <tr>
           <th>ID</th>
           <th>User
           </th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}

               <tr style="{%if not item.is_active%}color: red{%endif%}">
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{item.user}}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>
                       {% if item.is_active%}
                            {{ item.get_status_display }}
                       {% else %}
                            удален
                            <a href="{% url 'adminapp:order_recover' item.pk %}">
                                восcтановить
                            </a>
                       {% endif%}


                   </td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                            {% if item.is_active == True %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                            {% endif %}
                       {% endif %}
                   </td>
                   <td>
                    {%if item.is_active == True%}
                       <a href="{% url 'adminapp:order_status' item.pk %}">
                             Изменить статус
                       </a>
                    {%endif%}

                   </td>
               </tr>

           {% endfor %}
       </tbody>
   </table>
{% endblock %}

geekshop/adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div style="margin-left: 400px;">


<div class="form-horizontal">

     <div class="product_record">
        <img
          src="/media/{{product.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{product.name|title }}
            Категория: {{product.category}}
        </div>
     </div>
    <div>
        Краткое описание: {{ product.short_desc}}
    </div>
    <div>
        Описание: {{product.descriotion}}
    </div>
        <div>
       Цена: {{product.price}} $
    </div>
    <div>
        Количество: {{product.quantity}}
    </div>

</div>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_create.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_title%}
<div class="h2 text-center head">
    Создание
</div>
{% endblock %}


{% block content %}

  <form class="form-horizontal" method="post" enctype="multipart/form-data">
     {% csrf_token %}
      {{product_form.as_p}}
      {{product_gallery.as_p}}


    <input class="form-control" type="submit" value="сохранить">

  </form>

  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }}

    ?
    <form action="{% url 'admin:product_delete' product_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_title%}
<div class="h2 text-center head">
    Редактирование
</div>
{% endblock %}


{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    {{update_form_gallery.as_p}}

    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}

  <div class="products_list">
    <button class="new_product">
      <a href="{% url 'admin:product_create' category %}">
        новый продукт
      </a>
    </button>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 1</a>
                <a href="?page={{ page_obj.previous_page_number }}"><</a>
            {% endif %}

            <span class="current">
                стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">></a>
                <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% for object in object_list%}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href="{% url 'admin:product_read' object.pk %}">
              подробнее
            </a>
          </button>
          <button>
            <a href="{% url 'admin:product_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:product_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }} 
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_title%}
<div class="h2 text-center head">
    Редактирование
</div>
{% endblock %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href="{% url 'admin:user_create' %}">
        новый пользователь
      </a>
    </button>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 1</a>
                <a href="?page={{ page_obj.previous_page_number }}"><</a>
            {% endif %}

            <span class="current">
                стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">></a>
                <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% for object in object_list %}
      <div 
       class="user_record {% if not object.is_active %}not_active{% endif %}" style="height: 225px;">
        <img 
          src="{{ object.avatar|media_folder_users }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href="{% url 'admin:user_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:user_delete' object.pk %}">
              удалить
            </a>
          </button>
          <button>
            <a href="{% url 'admin:admin_orders' object.pk %}">
              Заказы
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	    <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}