geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'


urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    # path('products/', mainapp.products, name="products"),
    # path('product/', mainapp.product, name="product"),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace="admin")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name="index"),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class ProductCategory(models.Model):
    name = models.CharField(max_length=60, verbose_name="имя", unique=True)
    descriotion = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name="имя продукта")
    image = models.ImageField(upload_to="product_images", blank=True)
    short_desc = models.CharField(max_length=120, verbose_name="краткое описание продукта", blank=True)
    descriotion = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name="цена")
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True, db_index=True)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Gallery(models.Model):
    name_gallery = models.OneToOneField(Product, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    hot_image = models.ImageField(upload_to="hot_images", blank=True, default='hot_images/default.jpg')
    image_product = models.ImageField(upload_to="image_product", blank=True, default='image_product/default.jpg')

    @receiver(post_save, sender=Product)
    def create_gallery(sender, instance, created, **kwargs):
        if created:
            print('create')
            print(instance)

            Gallery.objects.create(name_gallery=instance)

    @receiver(post_save, sender=Product)
    def save_gallery(sender, instance, **kwargs):
        print(kwargs)

        print('save')
        instance.gallery.save()

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, ProductCategory, Gallery
from basketapp.models import Basket
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)

def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)

def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')

def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 2)[:2]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).filter(is_active=True).exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products

def hot_gallery(hot_game):
    hot_gallery = []
    for i in hot_game:
        print(i.name)
        image = Gallery.objects.filter(name_gallery=i.pk).select_related('name_gallery')
        print(hot_gallery.append(list(image)))
    return hot_gallery


def main(request):


    title = 'главная'
    list_game = get_products()[:4]
    content = {
        'games': list_game,
        "title": title,

    }
    return render(request, 'mainapp/index.html', content)

@cache_page(1)
def products(request, pk=None, page=1):
    count_product = 5

    title = 'галерея'
    list_categories = ProductCategory.objects.all()
    # hot_game = get_hot_product()
    # hot_image = hot_gallery(hot_game)
    #hot_image=[1,2]



    if pk is not None:
        if pk == 0:
            list_game = Product.objects.filter(is_active=True, category__is_active=True).order_by('price').select_related('category')
            category = {'name':'все', 'pk': 0}
        else:
            category = get_category(pk)
            print("+++")
            list_game = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(list_game, count_product)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
                'games': list_game,
                'categories': list_categories,
                "title": title,
                'pk_category': category,
                'products': products_paginator,

        }
        return render(request, 'mainapp/products_list.html', content)

    same_game = get_products()[1:4]

    content = {
        'games': same_game,
        'categories': list_categories,
        "title": title,
        #'hot_image': hot_image,

    }

    return render(request, 'mainapp/products.html', content)

@cache_page(1)
def product(request, pk):
    prod = get_product(pk)
    same_product = get_same_products(prod)
    print(same_product)
    title = 'продукты'
    img_gallery = Gallery.objects.filter(name_gallery=pk).select_related('name_gallery')
    # print(img_gallery[0].name_gallery, 'fdsfdsafa')
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'img_gallery': img_gallery,
        'same_product': same_product
    }
    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>
    {% block title %}
    {% endblock %}

    {% block head %}
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">

    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
        <script src="{% static 'js/product_script.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% endblock %}
</head>

<body>
    {% block content%}
    {% endblock %}

    {% block footer%}
        <div class="footer">
            <p class="footer-p">&copy; {% now "Y" %} Историческе Игры. Все права защищены</p>
        </div>
    {% endblock %}
</body>

</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block title %}
    <title>{{title|capfirst}}</title>
{% endblock %}
{% block content %}
    <div class="container-catalog">
        <div class="header">
            {% include 'mainapp/includes/inc_header_list.html' %}
        </div>
        <div class="menu catalog-menu">
                {% include 'mainapp/includes/inc_menu_catalogs.html' %}
        </div>

        <div class="container-product">

            <div class="img-product">
                <img class="img-prod" src="/media/{{ img_gallery.0.image_product }}" alt="">
            </div>
            <div class="text-product">
                <p class="product-game all-txt">{{product.name}}<span class="product-game price"><br>${{product.price}}</span></p>

                <h2 class="txt-prod">The plot is set in a fictional history of real world
                    events and follows the centuries-old struggle between the Assassins,
                    who fight for peace with free will, and the Templars, who desire peace
                    through control. The story is set in the mid-18th century during the Seven
                    Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who
                    hunts down former members of his Brotherhood after being betrayed by them
                    . Gameplay in Rogue is very similar to that of Black Flag with a mixture
                    of ship-based naval exploration and third-person land-based exploration
                    with some new features.</h2>
                <a href="{% url 'basket:add' product.pk %}" >
                    <button type="button" class="product-buy">
                                <p class="buy-buy buy-dis-p">Buy</p>
                    </button>
                </a>

            </div>

        </div>
        {% if same_product %}
        <div class="similar-games">
            <h class="similar-txt">
            </h>
            <div class="gallery-list gallery-list-catalog">
            {% for game in same_product%}
                    <div class="gallery-game">
                        <div class="img-gallery-game">

                            <a href="{% url 'products:product' game.pk %}">
                                <img src="/media/{{ game.image }}" alt="" class="img_game_gallery">
                            </a>
                            <h2 class="gallery-h2-game">{{game.name}}</h2>
                            <a href="{% url 'basket:add' game.pk %}" class="buy-button">
                                <p class="buy-buy">Buy</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends "mainapp/base.html" %}
{% load static %}


{% block title %}
    <title>{{title|capfirst}}</title>
{% endblock %}




{% block content %}
    <div class="container-catalog">
        <div class="header catalog-header">
            {% include 'mainapp/includes/inc_header_list.html' %}
        </div>
        </div>
        <div class="menu catalog-menu">
            {% include 'mainapp/includes/inc_menu_catalogs.html' %}
        </div>
        <div class="menu catalog-menu">

            {% include 'mainapp/includes/inc_menu_gallery.html'%}

        </div>
        <div class="gallery gallery-catalog">
            <h2 class="gallery-h2 gallery-catalog-h2">Our Gallery</h2>


            <div class="gallery-list gallery-list-catalog">
                {% for game in games%}
                    <div class="gallery-game">
                        <div class="img-gallery-game">

                            <a href="{% url 'products:product' game.pk %}">
                                <img src="/media/{{ game.image|default:'products_images/default.jpg' }}" alt="" class="img_game_gallery">
                            </a>
                            <h2 class="gallery-h2-game">{{game.name}}</h2>
                            <a href="{% url 'basket:add' game.pk %}" class="buy-button">
                                <p class="buy-buy">Buy</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <a href="{% url 'products:category' 0 %}" class="catalog-a">
                <div class="new-game">
                    <p class="catalog-p">Show more games &gt;</p>
                </div>
            </a>
        </div>

        <div class="list-block">
            {{hot_image}}

            {% for hot in hot_image%}
            {% if hot%}
                <div class="block">
                    <a href="{% url 'products:product' hot.0.name_gallery.pk %}">
                    <img src="/media/{{ hot.0.hot_image|default:'products_images/default.jpg' }}" alt="/products_images/default.jpg" class="hot_product">
                    </a>
                    <div class="content-block">
                        <p class="discont">discount</p>
                        <p class="discont-name">
                            {{hot.0.name_gallery.name}}
                        </p>
                        <p class="discont-price">${{hot.0.name_gallery.price}} </p>
                            <a href="{% url 'basket:add' hot.0.name_gallery.pk %}" class="discont-buy">
                                <p class="buy-buy buy-dis">Buy</p>
                            </a>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}
    <title>{{title|capfirst}}</title>
{% endblock %}


{% block content %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
                {{ message }}
        </div>
    {% endfor %}
    <div class="container-catalog">
        <div class="header catalog-header">
            {% include 'mainapp/includes/inc_header_list.html' %}
        </div>
        </div>
        <div class="menu catalog-menu">
            {% include 'mainapp/includes/inc_menu_catalogs.html' %}
        </div>
        <div class="menu catalog-menu">
                {% include 'mainapp/includes/inc_menu_gallery.html'%}
        </div>
        <div class="gallery gallery-catalog">
            <h2 class="gallery-h2 gallery-catalog-h2">{{pk_category.name}}{{u}}</h2>



                    <div class="Page navigation example">
                        <ul class="pagination justify-content-center">
                          {% if products.has_previous %}

                                   <li class="page-item" style="font-size: 15px;"> <a class="page-link"  href="{% url 'products:page' pk_category.pk products.previous_page_number%}">
                                 <span aria-hidden="true">&laquo;</span>
                                </a></li>
                              {% endif %}
                              <span class="current page-item page-link" style="font-size: 15px;">
                                страница {{ products.number }} из
                                {{ products.paginator.num_pages }}
                              </span>
                              {% if products.has_next %}
                               <li class="page-item" style="font-size: 15px;"> <a class="page-link"  href="{% url 'products:page' pk_category.pk products.next_page_number%}">
                                  <span aria-hidden="true">&raquo;</span>
                                </a></li>
                          {% endif %}
                            </ul>
                     </div>


            <div class="gallery-list gallery-list-catalog">
                {% for game in products%}
                    <div class="gallery-game">
                        <div class="img-gallery-game">

                            <a href="{% url 'products:product' game.pk %}">
                                <img src="{{game.image|media_folder_products}}" alt="" class="img_game_gallery">
                            </a>
                            <h2 class="gallery-h2-game">{{game.name}}</h2>
                            <a href="{% url 'basket:add' game.pk %}" class="buy-button">
                                <p class="buy-buy">Buy</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>

{% endblock %}